# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
x = s.split()
print(x)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [1]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers." .format(planet,diameter))

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

# Numpy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print (array)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np 
x = np.arange(0,9).reshape(3,3)
print(x)

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd
data=[10,20,30,40,50,60]
df=pd.DataFrame(data,columns=['Numbers'])
print(df)

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
from datetime import timedelta, date
def get_date_range(start,end):
    return[start+ timedelta(n) for n in range(int((end-start).days))]
print(get_date_range(date(2023,1,1), date(2023,2,11)))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
import pandas as pd 
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['S.no', 'name' , 'value'])
print(df)